export default {
  GET_STATE_LIST: 'GET_STATE_LIST',
  GET_MODEL_RESULT_STATE: 'GET_MODEL_RESULT_STATE',
  UPDATE_DATA: 'UPDATE_DATA',
  GET_LAST_DATE: 'GET_LAST_DATE',
  GET_MODEL_RESULTS: 'GET_MODEL_RESULTS',
};
